import { createHash } from "node:crypto";
export interface ExpansionRecipe { readonly recipeId: string; readonly recipeDigest: string; readonly maxItems: number; readonly maxItemBytes: number; readonly maxTotalBytes: number; }
export interface ExpansionRequest { readonly upstream: unknown; readonly upstreamPath: string; readonly idPrefix: string; readonly recipe: ExpansionRecipe; readonly workflowId?: string; readonly runId?: string; readonly workflowIntegrity?: string; readonly topologyDigest?: string; readonly upstreamNodeId?: string; readonly upstreamAttempt?: number; readonly upstreamRawDigest?: string; }
export interface ExpansionItem { readonly id: string; readonly index: number; readonly input: unknown; readonly digest: string; readonly bytes: number; }
export interface ExpansionManifest { readonly version: 1; readonly manifestId: string; readonly recipeId: string; readonly recipeDigest: string; readonly upstreamDigest: string; readonly items: readonly ExpansionItem[]; readonly totalBytes: number; readonly manifestDigest: string; readonly workflowId?: string; readonly runId?: string; readonly workflowIntegrity?: string; readonly topologyDigest?: string; readonly upstreamNodeId?: string; readonly upstreamAttempt?: number; readonly upstreamRawDigest?: string; }
const canonical = (value: unknown): string => value === null || typeof value !== "object" ? JSON.stringify(value) : Array.isArray(value) ? `[${value.map(canonical).join(",")}]` : `{${Object.keys(value as object).sort().map((key) => `${JSON.stringify(key)}:${canonical((value as Record<string, unknown>)[key])}`).join(",")}}`;
const bytes = (value: unknown): number => { const text = JSON.stringify(value); if (text === undefined) throw new Error("expansion input must be JSON data"); return Buffer.byteLength(text); };
const digest = (value: unknown): string => createHash("sha256").update(canonical(value)).digest("hex");
const pathGet = (value: unknown, path: string): unknown => { if (!/^\$((\.[A-Za-z0-9_-]+)|(\[[0-9]{1,6}\]))*$/.test(path)) throw new Error("upstream array path is invalid"); let current = value; for (const token of path.match(/\.[A-Za-z0-9_-]+|\[[0-9]{1,6}\]/g) ?? []) { const key = token.startsWith("[") ? Number(token.slice(1, -1)) : token.slice(1); if ((typeof key === "number" && !Array.isArray(current)) || current === null || typeof current !== "object" || !(key in (current as object))) throw new Error("upstream array path is unavailable"); current = (current as Record<string | number, unknown>)[key]; } return current; };
export function expandBounded(request: ExpansionRequest): ExpansionManifest {
  if (!request?.recipe || typeof request.recipe.recipeId !== "string" || !/^[a-f0-9]{64}$/.test(request.recipe.recipeDigest) || !/^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/.test(request.idPrefix)) throw new Error("expansion request is invalid");
  const source = pathGet(request.upstream, request.upstreamPath); if (!Array.isArray(source)) throw new Error("upstream path must select an array");
  const recipe = request.recipe; if (!Number.isInteger(recipe.maxItems) || recipe.maxItems < 1 || recipe.maxItems > 256 || !Number.isInteger(recipe.maxItemBytes) || recipe.maxItemBytes < 1 || recipe.maxItemBytes > 1_048_576 || !Number.isInteger(recipe.maxTotalBytes) || recipe.maxTotalBytes < 1 || recipe.maxTotalBytes > 16_777_216) throw new Error("expansion bounds are invalid"); if (source.length > recipe.maxItems) throw new Error("expansion item count exceeds bound");
  const seen = new Set<string>(); const seenInputIds = new Set<string>(); let totalBytes = 0;
  const items = source.map((input, index) => { const inputId = input && typeof input === "object" && !Array.isArray(input) && typeof (input as Record<string, unknown>).id === "string" ? (input as Record<string, unknown>).id as string : undefined; if (inputId !== undefined && (!/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/.test(inputId) || seenInputIds.has(inputId))) throw new Error("duplicate expansion input ID"); if (inputId !== undefined) seenInputIds.add(inputId); const itemBytes = bytes(input); if (itemBytes > recipe.maxItemBytes) throw new Error("expansion item exceeds bound"); totalBytes += itemBytes; if (totalBytes > recipe.maxTotalBytes) throw new Error("expansion total exceeds bound"); const id = `${request.idPrefix}.${String(index + 1).padStart(4, "0")}`; if (seen.has(id)) throw new Error("duplicate expansion ID"); seen.add(id); return Object.freeze({ id, index, input, digest: digest(input), bytes: itemBytes }); });
  const body = { version: 1 as const, manifestId: digest({ recipe: recipe.recipeDigest, upstream: digest(request.upstream), items: items.map((item) => ({ id: item.id, digest: item.digest })) }), recipeId: recipe.recipeId, recipeDigest: recipe.recipeDigest, upstreamDigest: digest(request.upstream), items, totalBytes, ...(request.workflowId ? { workflowId: request.workflowId } : {}), ...(request.runId ? { runId: request.runId } : {}), ...(request.workflowIntegrity ? { workflowIntegrity: request.workflowIntegrity } : {}), ...(request.topologyDigest ? { topologyDigest: request.topologyDigest } : {}), ...(request.upstreamNodeId ? { upstreamNodeId: request.upstreamNodeId } : {}), ...(request.upstreamAttempt ? { upstreamAttempt: request.upstreamAttempt } : {}), ...(request.upstreamRawDigest ? { upstreamRawDigest: request.upstreamRawDigest } : {}) };
  return Object.freeze({ ...body, manifestDigest: digest(body) });
}
export const expandAdaptiveFanOut = expandBounded;
export function validateExpansionManifest(value: unknown, request?: Pick<ExpansionRequest, "upstream" | "upstreamPath" | "idPrefix" | "recipe">): ExpansionManifest {
  if (!value || typeof value !== "object" || (value as Record<string, unknown>).version !== 1 || typeof (value as Record<string, unknown>).manifestDigest !== "string") throw new Error("expansion manifest is malformed");
  const manifest = value as ExpansionManifest; const allowedManifestKeys = new Set(["version", "manifestId", "recipeId", "recipeDigest", "upstreamDigest", "items", "totalBytes", "manifestDigest", "workflowId", "runId", "workflowIntegrity", "topologyDigest", "upstreamNodeId", "upstreamAttempt", "upstreamRawDigest"]); if (Object.keys(value as object).some((key) => !allowedManifestKeys.has(key)) || manifest.items?.some((item) => Object.keys(item as object).some((key) => !["id", "index", "input", "digest", "bytes"].includes(key)))) throw new Error("expansion manifest contains unknown fields"); if (manifest.workflowId !== undefined && (!/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/.test(manifest.workflowId) || !manifest.runId || !manifest.workflowIntegrity || !manifest.topologyDigest || !manifest.upstreamNodeId || !manifest.upstreamRawDigest || !Number.isInteger(manifest.upstreamAttempt))) throw new Error("expansion manifest binding is malformed"); if (manifest.workflowIntegrity !== undefined && !/^[a-f0-9]{64}$/.test(manifest.workflowIntegrity) || manifest.topologyDigest !== undefined && !/^[a-f0-9]{64}$/.test(manifest.topologyDigest) || manifest.upstreamRawDigest !== undefined && !/^[a-f0-9]{64}$/.test(manifest.upstreamRawDigest)) throw new Error("expansion manifest binding is malformed"); if (!Array.isArray(manifest.items) || manifest.items.length > 256 || !Number.isSafeInteger(manifest.totalBytes) || manifest.totalBytes < 0 || manifest.items.some((item, index) => !item || item.index !== index || item.id !== `${(manifest.items[0] as ExpansionItem)?.id?.replace(/\.\d{4}$/, "") ?? ""}.${String(index + 1).padStart(4, "0")}` || !/^[a-f0-9]{64}$/.test(item.digest) || item.digest !== digest(item.input) || !Number.isSafeInteger(item.bytes) || item.bytes < 0 || bytes(item.input) !== item.bytes) || new Set(manifest.items.map((item) => item?.id)).size !== manifest.items.length || manifest.items.reduce((total, item) => total + item.bytes, 0) !== manifest.totalBytes) throw new Error("expansion manifest is malformed");
  const expectedManifestId = digest({ recipe: manifest.recipeDigest, upstream: manifest.upstreamDigest, items: manifest.items.map((item) => ({ id: item.id, digest: item.digest })) }); if (manifest.manifestId !== expectedManifestId) throw new Error("expansion manifest identity mismatch"); const { manifestDigest: _digest, ...body } = manifest; if (manifest.manifestDigest !== digest(body)) throw new Error("expansion manifest digest mismatch"); if (request) { const expected = expandBounded(request); if (expected.manifestDigest !== manifest.manifestDigest) throw new Error("expansion manifest provenance mismatch"); } return manifest;
}
export const recoverExpansionManifest = validateExpansionManifest;
