import { createHash } from "node:crypto";
import type { WorkflowArtifactProvenance } from "./types.ts";

export type ArtifactProvenance = WorkflowArtifactProvenance;
const canonical = (value: unknown): string => value === null || typeof value !== "object" ? JSON.stringify(value) : Array.isArray(value) ? `[${value.map(canonical).join(",")}]` : `{${Object.keys(value as object).sort().map((key) => `${JSON.stringify(key)}:${canonical((value as Record<string, unknown>)[key])}`).join(",")}}`;
export function artifactDigest(value: unknown): string { return createHash("sha256").update(canonical(value)).digest("hex"); }
export const computeArtifactDigest = artifactDigest;
export function makeArtifactProvenance(input: Omit<WorkflowArtifactProvenance, "artifactDigest"> & { readonly value: unknown }): WorkflowArtifactProvenance { const { value, ...body } = input; const allowed = new Set(["version", "workflowId", "runId", "workflowIntegrity", "topologyDigest", "kind", "nodeId", "attempt", "artifactId", "capturedAt"]); if (Object.keys(body).some((key) => !allowed.has(key))) throw new Error("artifact provenance contains unknown fields"); if (!/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/.test(body.artifactId) || !/^[a-f0-9]{64}$/.test(body.workflowIntegrity) || !/^[a-f0-9]{64}$/.test(body.topologyDigest)) throw new Error("artifact provenance identity is invalid"); return Object.freeze({ ...body, artifactDigest: artifactDigest(value) }); }
export function assertArtifactProvenance(value: unknown, provenance: WorkflowArtifactProvenance, expected?: Partial<Pick<WorkflowArtifactProvenance, "workflowId" | "runId" | "workflowIntegrity" | "topologyDigest" | "kind" | "nodeId" | "attempt">>): void { if (expected && Object.entries(expected).some(([key, item]) => (provenance as unknown as Record<string, unknown>)[key] !== item)) throw new Error("artifact provenance ownership mismatch"); if (artifactDigest(value) !== provenance.artifactDigest) throw new Error("artifact provenance mismatch"); }
