import { createHash, randomUUID } from "node:crypto";
import type { TaskNode, WorkflowTopologySummary } from "./types.ts";
import type { CompiledWorkflow } from "./planner.ts";
export interface WorkflowRevision { readonly revision: number; readonly runId: string; readonly parentDigest: string; readonly workflowIntegrity: string; readonly topology: WorkflowTopologySummary; readonly invalidatedNodeIds: readonly string[]; readonly nodeDigests: Readonly<Record<string, string>>; }
const stable = (value: unknown): string => value === null || typeof value !== "object" ? JSON.stringify(value) : Array.isArray(value) ? `[${value.map(stable).join(",")}]` : `{${Object.keys(value as object).sort().map((key) => `${JSON.stringify(key)}:${stable((value as Record<string, unknown>)[key])}`).join(",")}}`;
const digest = (value: unknown): string => createHash("sha256").update(stable(value)).digest("hex");
export function stableNodeDigests(workflow: CompiledWorkflow): Readonly<Record<string, string>> { return Object.freeze(Object.fromEntries(workflow.nodes.map((node) => [node.id, digest(node)]))); }
export const computeStableNodeDigests = stableNodeDigests;
export function changedNodes(previous: CompiledWorkflow, revised: CompiledWorkflow): readonly string[] { const old = stableNodeDigests(previous), next = stableNodeDigests(revised); return revised.nodes.filter((node) => old[node.id] !== next[node.id]).map((node) => node.id).sort(); }
export const computeChangedNodes = changedNodes;
export function transitiveInvalidation(workflow: CompiledWorkflow, changed: readonly string[]): readonly string[] { const set = new Set(changed); const queue = [...changed]; while (queue.length) { const id = queue.shift()!; for (const dependent of workflow.dag.dependents.get(id) ?? []) if (!set.has(dependent)) { set.add(dependent); queue.push(dependent); } } return [...set].sort(); }
export function invalidatedNodeIds(previous: CompiledWorkflow, revised: CompiledWorkflow): readonly string[] { const changed = changedNodes(previous, revised); const removed = previous.nodes.filter((node) => !revised.dag.byId.has(node.id)).map((node) => node.id); return [...new Set([...transitiveInvalidation(previous, [...changed, ...removed]), ...transitiveInvalidation(revised, changed)])].sort(); }
export function createWorkflowRevision(previous: CompiledWorkflow, revised: CompiledWorkflow, revision: number, parentDigest: string): WorkflowRevision { if (!Number.isSafeInteger(revision) || revision < 2) throw new Error("revision must be at least 2"); if (parentDigest !== previous.integrity) throw new Error("revision parent digest mismatch"); const changed = changedNodes(previous, revised); const invalidated = transitiveInvalidation(revised, changed); if (!invalidated.length) throw new Error("revision does not change workflow nodes"); return Object.freeze({ revision, runId: randomUUID(), parentDigest, workflowIntegrity: revised.integrity, topology: revised.topology, invalidatedNodeIds: Object.freeze(invalidated), nodeDigests: stableNodeDigests(revised) }); }
export function assertFreshRevision(previous: WorkflowRevision, current: WorkflowRevision): void { if (previous.runId === current.runId || previous.workflowIntegrity === current.workflowIntegrity) throw new Error("workflow revision identity was reused"); if (current.parentDigest !== previous.workflowIntegrity) throw new Error("workflow revision provenance mismatch"); }
