import { createHash } from "node:crypto";
import type { WorkflowModel } from "./types.ts";
export interface ProviderTelemetry { readonly provider: "openai-codex"; readonly model: WorkflowModel; readonly requestId: string; readonly inputTokens: number; readonly outputTokens: number; readonly costUsd?: number; readonly runtimeMs: number; readonly capturedAt: number; readonly signature: string; }
export interface TelemetryBudget { readonly maxInputTokens: number; readonly maxOutputTokens: number; readonly maxCostUsd?: number; readonly maxRuntimeMs: number; readonly maxRequests: number; }
export interface TelemetryAggregate { readonly requestCount: number; readonly inputTokens: number; readonly outputTokens: number; readonly costUsd?: number; readonly runtimeMs: number; readonly digest: string; }
export interface ProviderTelemetryAdapter { readonly read: (requestId: string, signal?: AbortSignal) => Promise<ProviderTelemetry | undefined>; readonly verify: (telemetry: ProviderTelemetry) => boolean; }
export const unavailableProviderTelemetryAdapter: ProviderTelemetryAdapter = Object.freeze({ read: async () => undefined, verify: () => false });
const stable = (value: unknown): string => value === null || typeof value !== "object" ? JSON.stringify(value) : Array.isArray(value) ? `[${value.map(stable).join(",")}]` : `{${Object.keys(value as object).sort().map((key) => `${JSON.stringify(key)}:${stable((value as Record<string, unknown>)[key])}`).join(",")}}`;
const digest = (value: unknown): string => createHash("sha256").update(stable(value)).digest("hex");
export function validateProviderTelemetry(value: unknown): ProviderTelemetry { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("provider telemetry is unavailable or malformed"); const item = value as Record<string, unknown>; if (item.provider !== "openai-codex" || typeof item.model !== "string" || !/^openai-codex\/gpt-5\.6-(luna|sol)$/.test(item.model) || typeof item.requestId !== "string" || !/^[A-Za-z0-9._:-]{1,256}$/.test(item.requestId) || !Number.isSafeInteger(item.inputTokens) || (item.inputTokens as number) < 0 || !Number.isSafeInteger(item.outputTokens) || (item.outputTokens as number) < 0 || !Number.isSafeInteger(item.runtimeMs) || (item.runtimeMs as number) < 0 || !Number.isSafeInteger(item.capturedAt) || (item.capturedAt as number) < 0 || typeof item.signature !== "string" || !/^[a-f0-9]{64,}$/.test(item.signature)) throw new Error("provider telemetry is unavailable or malformed"); if (item.costUsd !== undefined && (typeof item.costUsd !== "number" || !Number.isFinite(item.costUsd) || item.costUsd < 0)) throw new Error("provider telemetry cost is malformed"); return item as unknown as ProviderTelemetry; }
export function validateTelemetryBudget(budget: TelemetryBudget): TelemetryBudget { if (!budget || !Number.isSafeInteger(budget.maxRequests) || budget.maxRequests < 1 || budget.maxRequests > 10000 || !Number.isSafeInteger(budget.maxInputTokens) || budget.maxInputTokens < 0 || budget.maxInputTokens > 100_000_000 || !Number.isSafeInteger(budget.maxOutputTokens) || budget.maxOutputTokens < 0 || budget.maxOutputTokens > 100_000_000 || !Number.isSafeInteger(budget.maxRuntimeMs) || budget.maxRuntimeMs < 1 || budget.maxRuntimeMs > 86_400_000 || budget.maxCostUsd !== undefined && (!Number.isFinite(budget.maxCostUsd) || budget.maxCostUsd < 0 || budget.maxCostUsd > 1_000_000)) throw new Error("invalid telemetry budget"); return Object.freeze({ ...budget }); }
export function aggregateTelemetry(items: readonly ProviderTelemetry[], budget: TelemetryBudget): TelemetryAggregate { validateTelemetryBudget(budget); if (!Number.isSafeInteger(budget.maxRequests) || budget.maxRequests < 1 || items.length > budget.maxRequests) throw new Error("telemetry request budget exceeded"); let inputTokens = 0, outputTokens = 0, runtimeMs = 0, costUsd = 0; let hasCost = false; for (const raw of items) { const item = validateProviderTelemetry(raw); inputTokens += item.inputTokens; outputTokens += item.outputTokens; runtimeMs += item.runtimeMs; if (budget.maxCostUsd !== undefined && item.costUsd === undefined) throw new Error("provider telemetry cost is required when maxCostUsd is configured"); if (item.costUsd !== undefined) { costUsd += item.costUsd; hasCost = true; } } if (inputTokens > budget.maxInputTokens || outputTokens > budget.maxOutputTokens || runtimeMs > budget.maxRuntimeMs || hasCost && budget.maxCostUsd !== undefined && costUsd > budget.maxCostUsd) throw new Error("telemetry budget exceeded"); const body = { requestCount: items.length, inputTokens, outputTokens, ...(hasCost ? { costUsd } : {}), runtimeMs }; return Object.freeze({ ...body, digest: digest(body) }); }
export async function requireProviderTelemetry(adapter: ProviderTelemetryAdapter | undefined, requestIds: readonly string[], budget: TelemetryBudget, signal?: AbortSignal): Promise<{ readonly items: readonly ProviderTelemetry[]; readonly aggregate: TelemetryAggregate }> { validateTelemetryBudget(budget); if (!adapter || typeof adapter.read !== "function" || typeof adapter.verify !== "function") throw new Error("provider telemetry is required but unavailable"); if (requestIds.length > budget.maxRequests) throw new Error("telemetry request budget exceeded"); const items: ProviderTelemetry[] = []; for (const id of requestIds) { const item = await adapter.read(id, signal); if (!item) throw new Error("provider telemetry is required but unavailable"); const checked = validateProviderTelemetry(item); if (adapter.verify && adapter.verify(checked) !== true) throw new Error("provider telemetry signature verification failed"); items.push(checked); } return Object.freeze({ items: Object.freeze(items), aggregate: aggregateTelemetry(items, budget) }); }
